# Generated by Django 3.0.2 on 2020-04-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusrequest',
            options={'verbose_name_plural': 'Contact Queries'},
        ),
        migrations.AddField(
            model_name='contactusrequest',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
