# Generated by Django 3.0.2 on 2020-01-27 13:29

import diving.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('e_learning_link', models.CharField(blank=True, max_length=255, null=True)),
                ('min_age', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('pool_dives', models.BooleanField(default=False)),
                ('ocean_dives', models.BooleanField(default=True)),
                ('num_pool_dives', models.IntegerField(blank=True, null=True)),
                ('num_ocean_dives', models.IntegerField(blank=True, null=True)),
                ('minimum_certiication_level', models.CharField(blank=True, choices=[('Discover Scuba Diver', 'Discover Scuba Diver'), ('Junior Scuba Diver', 'Junior Scuba Diver'), ('Open Water', 'Open Water'), ('Advanced Open Water', 'Advanced Open Water'), ('Rescue Diver', 'Rescue Diver'), ('Deep Specialty', 'Deep Specialty')], max_length=255, null=True)),
                ('qualified_to', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiveBookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cert_level', models.CharField(blank=True, choices=[('Discover Scuba Diver', 'Discover Scuba Diver'), ('Junior Scuba Diver', 'Junior Scuba Diver'), ('Open Water', 'Open Water'), ('Advanced Open Water', 'Advanced Open Water'), ('Rescue Diver', 'Rescue Diver'), ('Deep Specialty', 'Deep Specialty')], max_length=255, null=True)),
                ('time', models.CharField(blank=True, choices=[('9am', '9am'), ('1:30pm', '1:30pm')], max_length=255, null=True)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiveTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trip_type', models.CharField(blank=True, choices=[('boat-dive', 'Boat Dive'), ('shore-dive', 'Shore Dive')], max_length=255, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dive Trips',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=diving.model_utils.image_path)),
                ('thumbnail', models.ImageField(editable=False, null=True, upload_to=diving.model_utils.thumbnail_path)),
                ('hero_image', models.ImageField(editable=False, null=True, upload_to=diving.model_utils.hero_path)),
                ('medium_image', models.ImageField(editable=False, null=True, upload_to=diving.model_utils.medium_path)),
                ('mobile_image', models.ImageField(editable=False, null=True, upload_to=diving.model_utils.mobile_path)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255)),
                ('course_pic', models.BooleanField(default=False)),
                ('dive_site_pic', models.BooleanField(default=False)),
                ('dive_trip_pic', models.BooleanField(default=False)),
                ('marine_life_pic', models.BooleanField(default=False)),
                ('client_pic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='MarineLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abundance', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Images')),
            ],
            options={
                'verbose_name_plural': 'Marine Life',
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('learning_type', models.CharField(blank=True, choices=[('e-learning', 'E-learning'), ('book-learning', 'Book-learning')], max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('dive_trip_equipment', models.CharField(blank=True, choices=[('FK', 'Full Kit'), ('TW', 'Tanks and Weights'), ('EXCL', 'Excluding Equipment')], max_length=255, null=True)),
                ('trip_type', models.CharField(blank=True, choices=[('boat-dive', 'Boat Dive'), ('shore-dive', 'Shore Dive')], max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Category')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cert_level', models.CharField(blank=True, choices=[('Discover Scuba Diver', 'Discover Scuba Diver'), ('Junior Scuba Diver', 'Junior Scuba Diver'), ('Open Water', 'Open Water'), ('Advanced Open Water', 'Advanced Open Water'), ('Rescue Diver', 'Rescue Diver'), ('Deep Specialty', 'Deep Specialty')], max_length=255, null=True)),
                ('course_booking_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_diver', to='diving.DiveBookingRequest')),
                ('dive_booking_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_diver', to='diving.CourseBookingRequest')),
            ],
        ),
        migrations.CreateModel(
            name='DiveTripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=600)),
                ('text', models.TextField()),
                ('dive_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='diving.DiveTrip')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Images')),
            ],
            options={
                'verbose_name_plural': 'Dive Trip Info',
            },
        ),
        migrations.AddField(
            model_name='divetrip',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Images'),
        ),
        migrations.CreateModel(
            name='DiveSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('min_diver_level', models.CharField(blank=True, choices=[('Discover Scuba Diver', 'Discover Scuba Diver'), ('Junior Scuba Diver', 'Junior Scuba Diver'), ('Open Water', 'Open Water'), ('Advanced Open Water', 'Advanced Open Water'), ('Rescue Diver', 'Rescue Diver'), ('Deep Specialty', 'Deep Specialty')], max_length=255, null=True)),
                ('site_type', models.CharField(blank=True, choices=[('Ship Wreck', 'Ship Wreck'), ('Coral Reef', 'Coral Reef'), ('Artificial / Reef', 'Artificial / Reef')], max_length=255, null=True)),
                ('dive_time', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('map_image', models.ImageField(default='map_default.jpg', upload_to=diving.model_utils.image_path)),
                ('marine_life', models.ManyToManyField(to='diving.MarineLife')),
            ],
            options={
                'verbose_name_plural': 'Dive Sites',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('info_type', models.CharField(blank=True, choices=[('e-learning-info', 'e-learning-info'), ('book-learning-info', 'book-learning-info'), ('pool-info', 'pool-info'), ('ocean-info', 'ocean-info')], max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Images')),
            ],
            options={
                'verbose_name_plural': 'Course Info',
            },
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('answer', models.TextField()),
                ('courses', models.ManyToManyField(blank=True, related_name='faq', to='diving.Course')),
            ],
            options={
                'verbose_name_plural': "Course FAQ's",
            },
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Images'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='diving.Category'),
        ),
        migrations.CreateModel(
            name='ClientTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('images', models.ManyToManyField(blank=True, to='diving.Images')),
            ],
            options={
                'verbose_name_plural': "Course FAQ's",
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Images'),
        ),
    ]
