# Generated by Django 3.0 on 2020-03-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0002_auto_20200301_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='info_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_image', to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overview_image', to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedule_image', to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='divetrip',
            name='description_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_image', to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='divetrip',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='divetrip',
            name='schedule_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_image', to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='divetripinfo',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Image', to_field='title'),
        ),
        migrations.AlterField(
            model_name='marinelife',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diving.Image', to_field='title'),
        ),
    ]
