# Generated by Django 3.0.2 on 2020-01-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0002_auto_20200129_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divebookingrequest',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='divebookingrequestdiver',
            name='dive_booking_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divers', to='diving.DiveBookingRequest'),
        ),
    ]
