# Generated by Django 3.0.2 on 2020-01-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0003_auto_20200129_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='divebookingrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='minimum_certiication_level',
            field=models.CharField(blank=True, choices=[('Junior Scuba Diver', 'Junior Scuba Diver'), ('Open Water', 'Open Water'), ('Advanced Open Water', 'Advanced Open Water'), ('Rescue Diver', 'Rescue Diver'), ('Deep Specialty', 'Deep Specialty')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='divebookingrequestdiver',
            name='cert_level',
            field=models.CharField(blank=True, choices=[('Junior Scuba Diver', 'Junior Scuba Diver'), ('Open Water', 'Open Water'), ('Advanced Open Water', 'Advanced Open Water'), ('Rescue Diver', 'Rescue Diver'), ('Deep Specialty', 'Deep Specialty')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='divebookingrequestdiver',
            name='kit_required',
            field=models.CharField(blank=True, choices=[('Full Kit', 'Full Kit'), ('Tanks and Weights', 'Tanks and Weights'), ('Excluding Equipment', 'Excluding Equipment')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='divesite',
            name='marine_life',
            field=models.ManyToManyField(blank=True, to='diving.MarineLife'),
        ),
        migrations.AlterField(
            model_name='divesite',
            name='min_diver_level',
            field=models.CharField(blank=True, choices=[('Junior Scuba Diver', 'Junior Scuba Diver'), ('Open Water', 'Open Water'), ('Advanced Open Water', 'Advanced Open Water'), ('Rescue Diver', 'Rescue Diver'), ('Deep Specialty', 'Deep Specialty')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='diving.Category'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='dive_trip_equipment',
            field=models.CharField(blank=True, choices=[('Full Kit', 'Full Kit'), ('Tanks and Weights', 'Tanks and Weights'), ('Excluding Equipment', 'Excluding Equipment')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='learning_type',
            field=models.CharField(blank=True, choices=[('E-Learning', 'E-Learning'), ('Book-Learning', 'Book-Learning')], max_length=255, null=True),
        ),
    ]
