# Generated by Django 3.0 on 2020-03-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0004_auto_20200301_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='dive_trip',
        ),
    ]
