# Generated by Django 3.0.2 on 2020-02-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0004_auto_20200129_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overview_image', to='diving.Images'),
        ),
    ]
