# Generated by Django 3.0.2 on 2020-04-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0006_auto_20200301_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='divebookingrequest',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('boat-dive', 'Boat Dive'), ('shore-dive', 'Shore Dive')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='divebookingrequest',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
