# Generated by Django 3.0.2 on 2020-02-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0008_auto_20200213_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='dive_trip',
        ),
    ]
