# Generated by Django 3.0.2 on 2020-02-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0010_itemprice_dive_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='divetrip',
            name='schedule_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_image', to='diving.Images'),
        ),
    ]
