# Generated by Django 3.0.2 on 2020-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0012_divetrip_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='divetrip',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
