# Generated by Django 3.0.2 on 2020-02-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0013_divetrip_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedule_image', to='diving.Images'),
        ),
    ]
